# -*- coding: utf-8 -*-
"""計概hw1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10kRf6Mc1FOCGyOWxtkCzEqhntgIQ92VW
"""

x=5
print(f"變數x的值是:{x}")
print(f"變數x的記憶體地址是:{id(x)}")